### ISSUE TITLE
EPIC: as traffic manager I would like to integrate A22 parking data in the Open Data Hub

### ISSUE THREAD

**Issue by rcavaliere** [noi-techpark/bdp-commons#248]
This user story deals with the integration of the parking data traffic events in the ODH. The implementation is implemented by 1006.org and Catch&Solve. 

Tasks covered by this epic:

- [x] Implementation of the connector to the A22 interface (by 1006.org)
- [x] specification of the adapter with the ODH data model (by @rcavaliere)
- [x] implementation of the adapter to the ODH (by Catch&Solve)
- [x] preparation of the repository + pipeline (by @bertolla)

**Comment by davidebz** [comment]
Hi,

Thomas has send a PR for the parking part. It can be but in testing environment.

**Comment by davidebz** [comment]
As discuss in the email betwenn Roberto and Davide (31/05/21, 18:22
), we can't modify the active flag, this should be made by the "writer"

**Comment by davidebz** [comment]
Note: until now the "posti_liberi" is always null except sadobre
All have capacità (as metadata) and stato (0,1,2)

**Comment by rcavaliere** [comment]
@davidebz thanks! One question: the type "posti_liberi" is returned for all parking areas? Because if it is available just for the Sadobre parking area, I would avoid to foresee this data type for all the other parking area, since we will have there just unuseless time series with just "null" values...

**Comment by bertolla** [comment]
@rcavaliere which a22 user can I use? As I remember we can't use the same user in 2 different dc's.
Is there still one I can use?

**Comment by rcavaliere** [comment]
@bertolla I forwarded to you via e-mail the credentials to be used.

**Comment by bertolla** [comment]
I put everything on testing, to me it seems that there is only data pouring in from 'SADOBRE', but maybe it's better if you test @rcavaliere

**Comment by rcavaliere** [comment]
@davidebz I have tested the Data Collector. In general, everything works as expected.
I would however propose an improvement. If you look at the metadata saved for the parking area "Sadobre" you will see different records, since the fields "stato" and "capacità" seem to vary quite frequently. I do not understand why the field "capacity" change, since usually it is fixed. My proposal would be to keep "capacity" as an attribute of the metadata table, but on the other side to consider "stato"  an additional type. In this way, we will see data associated to all other parking areas different from "Sadobre". That was actually my original thought (see attached specification proposal), which I would confirm now that I see some data stored.
[210525_SpecificheIntegrazione_A22_Parcheggi_v2.docx](https://github.com/noi-techpark/bdp-commons/files/6713939/210525_SpecificheIntegrazione_A22_Parcheggi_v2.docx)

Can you please improve the Data Collector and make a new PR?

**Comment by noctho** [comment]
>Can you please improve the Data Collector and make a new PR?

done. see #287

**Comment by rcavaliere** [comment]
@noctho @davidebz Data Collector tested, works as expected. Wonderful!
@bertolla please put it in production. Remember: data should be closed and accessible only from the BrennerLEC user group

**Comment by bertolla** [comment]
Yes, I deployed on Jun "25 12:28". I deployed it just now once more just to be sure(always on test)

**Comment by rcavaliere** [comment]
@bertolla I don't understand. It is still not in production, or?

**Comment by bertolla** [comment]
No, it never went on production.
What happened:
pull-request-> deployment on test -> missing feature -> davide fixed problem/new pull request -> deployed on test on june 25. -> now

**Comment by rcavaliere** [comment]
ok, now we can go in production! :-)
