### ISSUE TITLE
EPIC: as traffic manager I would like to integrate the bike counter dataset of the Municipality of Bolzano

### ISSUE THREAD

**Issue by rcavaliere** [noi-techpark/bdp-commons#249]
The  Municipality of Bolzano has given a contract to Famas System to implement an API for sharing with the Open Data Hub the bike counter data collected through several sensors on the bike lanes in the city.
The access to the data is similar to the traffic data provided by the Municipality of Bolzano, we should however call port 5002.
Tasks to do:
- [x] test the connection (by @bertolla)
- [x] specify the data integration modalities (by @rcavaliere)
- [x] configuration of the new data collector instance (by @bertolla )
- [x] prepare the repository and pipeline on github (by @bertolla)

The interface is SOAP and the data structure is very similar to the traffic DC. I would therefore suggest to try to implement the DC internally by starting from the traffic DC and just adjusting the mapping scheme with the ODH model, where necessary. In this case @bertolla could do the work, I guess.

**Comment by rcavaliere** [comment]
@bertolla here some indications for the mapping with ODH core
[210420_SpecificheIntegrationeODH.pdf](https://github.com/noi-techpark/bdp-commons/files/6343168/210420_SpecificheIntegrationeODH.pdf)

**Comment by bertolla** [comment]
@rcavaliere 
- The connection works only through the ip where we have the traffic datacollector on port 5002. We need to switch that they open for every ip of a domain we specify
- I need the wsdl to be able to do anything
- The old endpoint is http://109.117.22.203:5001/DataDispatcherWebServices.asmx . What is the new endpoint?

**Comment by rcavaliere** [comment]
@bertolla 

> The connection works only through the ip where we have the traffic datacollector on port 5002. We need to switch that they open for every ip of a domain we specify

Can you please provide the IP addresses you want to use for the tests

> I need the wsdl to be able to do anything

I can't upload a WSDL on github, I send this via e-nail

> The old endpoint is http://109.117.22.203:5001/DataDispatcherWebServices.asmx . What is the new endpoint?

The new endpoint should be the same. Try and if not tell me that I ask for clarifications

> If the API is different we still would need to write the dc from scratch and we can't really reuse the existing datacollector

The API should be fast the same, with some small adaptions in my view you can reuse the existing data collector

**Comment by bertolla** [comment]
> @bertolla
> 
> > The connection works only through the ip where we have the traffic datacollector on port 5002. We need to switch that they open for every ip of a domain we specify
> 
> Can you please provide the IP addresses you want to use for the tests
> 
I would not provide you an ip but we would use a domain like for example: `comunebz.opendatahub.bz.it`. You would need to ask if they can open their firewall for a domain.

> > I need the wsdl to be able to do anything
> 
> I can't upload a WSDL on github, I send this via e-nail

I got it :+1: 

> 
> > The old endpoint is http://109.117.22.203:5001/DataDispatcherWebServices.asmx . What is the new endpoint?
> 
> The new endpoint should be the same. Try and if not tell me that I ask for clarifications
> 
It's not the same, I found out by trial end error. It's http://109.117.22.203:5002/BiciCountDispatcherWs.asmx

> > If the API is different we still would need to write the dc from scratch and we can't really reuse the existing datacollector
> 
> The API should be fast the same, with some small adaptions in my view you can reuse the existing data collector

Seems to be working. One thing I would need to know how are the mapping of types now? In traffic we had this mapping file: https://github.com/noi-techpark/bdp-commons/blob/master/data-collectors/traffic-bz/src/main/resources/META-INF/spring/types.properties

**Comment by rcavaliere** [comment]
@bertolla I asked the Municipality of BZ about the access through a certain domain and Famas System for the specifications. Can you provide me the log issue with the traffic data collector with the Municipality?

**Comment by rcavaliere** [comment]
@bertolla The Municipality of BZ has already replied. They can only set IP addresses.

**Comment by rcavaliere** [comment]
Status:
-> first tests completed
-> API document insufficient, asking for more specifications (waiting for feedback)
-> issue with access limitation, possible to allow only certain IPs, suboptimal situation in terms of server infrastructure on AWS. @bertolla @Piiit how do you suggest to improve this situation?
-> still to be understood the effort to develop this new DC on top of https://github.com/noi-techpark/bdp-commons/tree/master/data-collectors/traffic-bz

**Comment by Piiit** [comment]
@rcavaliere We could probably have a set of static IPs that we never change and just redirect internally with some route53 configs on AWS. We could then have some CNAMEs for instance or a reverse proxy installation. Another solution could be that we connect via VPN (but I would not recommend this approach, since it introduces technical depth and additional problems for sure)... or as last resort, we could give them an IP and they connect to us, then we could create a tunnel to their infrastructure (ssh tunnel) or websockets... but the latter two ideas are also not recommended. So the easiest is just to have some IPs that never change and use those solely for externals (probably, if we have more connectors, use different port ranges).

**Comment by bertolla** [comment]
@rcavaliere 
Data is inside test db, test here:
https://mobility.api.opendatahub.testingmachine.eu/v2/flat/BikeCounter/*/latest
https://mobility.api.opendatahub.testingmachine.eu/v2/flat/BikeCounter/
Can you update analytics?

**Comment by rcavaliere** [comment]
Super! To see data on analytics we need a small development work, also in terms of UX / UI...  @sseppi do we have open contracts with externals such as Made in Cima to ask for such small things, e.g. a new icon / colour for analytics?

**Comment by rcavaliere** [comment]
@bertolla seems to work fine. Just two things:
- [ ] at present we have period = 1 in the measurement / measurementhistory tables. I would put 3600 since the data has a hourly resolution
- [ ] looking at the time series I think we have some timezone issue. The peak is at 5 AM which is not reasonable. I guess it is 7 AM

**Comment by bertolla** [comment]
@rcavaliere 
Just having a glance on a random dataset(Via Parma - Verso Nord) I don't think it is the case:
```
     id     |       created_on        | period |      timestamp      | double_value | provenance_id | station_id | type_id 
------------+-------------------------+--------+---------------------+--------------+---------------+------------+---------
 2199531469 | 2021-06-07 13:11:44.727 |   3600 | 2021-06-07 01:00:00 |            2 |           124 |     349798 |      16
 2199531468 | 2021-06-07 13:11:44.726 |   3600 | 2021-06-07 00:00:00 |            4 |           124 |     349798 |      16
 2199531355 | 2021-06-07 13:11:41.456 |   3600 | 2021-06-06 23:00:00 |            2 |           124 |     349798 |      16
 2199531354 | 2021-06-07 13:11:41.456 |   3600 | 2021-06-06 22:00:00 |            0 |           124 |     349798 |      16
 2199531353 | 2021-06-07 13:11:41.455 |   3600 | 2021-06-06 21:00:00 |            3 |           124 |     349798 |      16
 2199531352 | 2021-06-07 13:11:41.455 |   3600 | 2021-06-06 20:00:00 |            9 |           124 |     349798 |      16
 2199531351 | 2021-06-07 13:11:41.454 |   3600 | 2021-06-06 19:00:00 |           29 |           124 |     349798 |      16
 2199531350 | 2021-06-07 13:11:41.454 |   3600 | 2021-06-06 18:00:00 |           41 |           124 |     349798 |      16
 2199531349 | 2021-06-07 13:11:41.453 |   3600 | 2021-06-06 17:00:00 |           37 |           124 |     349798 |      16
 2199531348 | 2021-06-07 13:11:41.452 |   3600 | 2021-06-06 16:00:00 |           85 |           124 |     349798 |      16
 2199531347 | 2021-06-07 13:11:41.452 |   3600 | 2021-06-06 15:00:00 |           80 |           124 |     349798 |      16
 2199531346 | 2021-06-07 13:11:41.451 |   3600 | 2021-06-06 14:00:00 |           75 |           124 |     349798 |      16
 2199531345 | 2021-06-07 13:11:41.451 |   3600 | 2021-06-06 13:00:00 |           32 |           124 |     349798 |      16
 2199531344 | 2021-06-07 13:11:41.45  |   3600 | 2021-06-06 13:00:00 |           28 |           124 |     349798 |      16
 2199531343 | 2021-06-07 13:11:41.45  |   3600 | 2021-06-06 12:00:00 |           55 |           124 |     349798 |      16
 2199531342 | 2021-06-07 13:11:41.449 |   3600 | 2021-06-06 11:00:00 |           61 |           124 |     349798 |      16
 2199531341 | 2021-06-07 13:11:41.449 |   3600 | 2021-06-06 10:00:00 |           76 |           124 |     349798 |      16
 2199531340 | 2021-06-07 13:11:41.448 |   3600 | 2021-06-06 09:00:00 |          100 |           124 |     349798 |      16
 2199531339 | 2021-06-07 13:11:41.447 |   3600 | 2021-06-06 08:00:00 |          101 |           124 |     349798 |      16
 2199531338 | 2021-06-07 13:11:41.447 |   3600 | 2021-06-06 07:00:00 |           65 |           124 |     349798 |      16
 2199531337 | 2021-06-07 13:11:41.446 |   3600 | 2021-06-06 06:00:00 |           28 |           124 |     349798 |      16
 2199531336 | 2021-06-07 13:11:41.446 |   3600 | 2021-06-06 05:00:00 |            8 |           124 |     349798 |      16
 2199531335 | 2021-06-07 13:11:41.445 |   3600 | 2021-06-06 04:00:00 |            3 |           124 |     349798 |      16
 2199531334 | 2021-06-07 13:11:41.444 |   3600 | 2021-06-06 03:00:00 |            2 |           124 |     349798 |      16
 2199531333 | 2021-06-07 13:11:41.444 |   3600 | 2021-06-06 02:00:00 |            0 |           124 |     349798 |      16

```
Can you show me the data which is wrong?

**Comment by rcavaliere** [comment]
OK, I have to make another look at the data. It seemed to me that certain measurement points had another behavior....

**Comment by bertolla** [comment]
This is the reuslt:
```
 station_id |      timetamp       |         created         
------------+---------------------+-------------------------
     349830 | 2021-06-08 04:00:00 | 2021-06-08 05:10:03.565
     349831 | 2021-06-08 04:00:00 | 2021-06-08 05:10:03.584
     349822 | 2021-06-08 03:00:00 | 2021-06-08 03:10:03.63
     349823 | 2021-06-08 03:00:00 | 2021-06-08 03:10:03.649
     349824 | 2021-06-08 03:00:00 | 2021-06-08 03:10:03.668
     349825 | 2021-06-08 03:00:00 | 2021-06-08 03:10:03.681
     349826 | 2021-06-08 03:00:00 | 2021-06-08 03:10:03.695
     349827 | 2021-06-08 03:00:00 | 2021-06-08 03:10:03.715
     349812 | 2021-06-08 02:00:00 | 2021-06-08 02:20:03.3
     349813 | 2021-06-08 02:00:00 | 2021-06-08 02:20:03.312
     349814 | 2021-06-08 02:00:00 | 2021-06-08 02:20:03.325
     349815 | 2021-06-08 02:00:00 | 2021-06-08 02:20:03.337
     349816 | 2021-06-08 02:00:00 | 2021-06-08 02:20:03.35
     349817 | 2021-06-08 02:00:00 | 2021-06-08 02:20:03.361
     349818 | 2021-06-08 02:00:00 | 2021-06-08 02:20:03.373
     349819 | 2021-06-08 02:00:00 | 2021-06-08 02:20:03.387
     349820 | 2021-06-08 02:00:00 | 2021-06-08 02:20:03.399
     349821 | 2021-06-08 02:00:00 | 2021-06-08 02:20:03.41
     349794 | 2021-06-08 01:00:00 | 2021-06-08 01:30:07.303
     349795 | 2021-06-08 01:00:00 | 2021-06-08 01:30:07.294
     349796 | 2021-06-08 01:00:00 | 2021-06-08 01:30:07.323
     349797 | 2021-06-08 01:00:00 | 2021-06-08 01:30:07.313
     349798 | 2021-06-08 01:00:00 | 2021-06-08 01:30:07.342
     349799 | 2021-06-08 01:00:00 | 2021-06-08 01:30:07.333
     349806 | 2021-06-08 01:00:00 | 2021-06-08 02:10:04.015
     349807 | 2021-06-08 01:00:00 | 2021-06-08 02:10:04.028
     349808 | 2021-06-08 01:00:00 | 2021-06-08 02:10:04.039
     349809 | 2021-06-08 01:00:00 | 2021-06-08 02:10:04.05
     349810 | 2021-06-08 01:00:00 | 2021-06-08 02:10:04.06
     349811 | 2021-06-08 01:00:00 | 2021-06-08 02:10:04.073
     349800 | 2021-06-08 00:00:00 | 2021-06-08 01:30:07.257
     349801 | 2021-06-08 00:00:00 | 2021-06-08 01:30:07.267
     349802 | 2021-06-08 00:00:00 | 2021-06-08 01:30:07.275
     349803 | 2021-06-08 00:00:00 | 2021-06-08 01:30:07.284
     349790 | 2021-06-07 22:00:00 | 2021-06-07 22:30:04.211
     349791 | 2021-06-07 22:00:00 | 2021-06-07 22:30:04.238
     349804 | 2021-05-21 12:00:00 | 2021-06-07 13:10:14.713
     349805 | 2021-05-21 12:00:00 | 2021-06-07 13:10:14.76
```

From this data I can derive that:
- there is no timezone issue, since the difference of time when it was created and when it was measured is never even close to 2 hours
- the last record timestamp differs from station to station
- the difference between the time the dataset gets measured and exposed through the webservice differs considerably(20-70 minutes)

**Comment by rcavaliere** [comment]
@bertolla wonderful. Is this dataset already available via API? I don't see it.

**Comment by bertolla** [comment]
Since the synchronization is running once a day in the morning, you will need to wait till tomorrow

**Comment by rcavaliere** [comment]
Famas has fixed the coordinates issues. Data is OK, we can put the DC in production
