### ISSUE TITLE
EPIC: as a project manager I would like to integrate the real-time data of the on-demand service of MENTOR

### ISSUE THREAD

**Issue by rcavaliere** [noi-techpark/bdp-commons#289]
High Priority, Deadline 31 September

The Data Collector is developed by Catch&Solve. Tasks foreseen:
- [x] creation of repository + CI pipeline
- [x] data model definition ("mapping" between data availability and ODH model)
- [x] Data Collector development

Details available here: 
[210616_RichiestaOfferte.pdf](https://github.com/noi-techpark/bdp-commons/files/6857144/210616_RichiestaOfferte.pdf)

**Comment by bertolla** [comment]
@rcavaliere Could you please send me the username and share the password through passbolt?
https://github.com/noi-techpark/bdp-commons/blob/development/data-collectors/on-demand-merano/src/main/resources/connector.properties

**Comment by rcavaliere** [comment]
@bertolla just forwarded via secure mail

**Comment by rcavaliere** [comment]
@bertolla let me know when the DC is up and running in the test environment

**Comment by bertolla** [comment]
I deployed on test but it throws exceptions:
```
[ERROR] 2021-08-16 09:44:50.309 [Scheduler-8] MainOnDemandMerano - elaborate itinerary failed
app_1  | org.springframework.web.reactive.function.client.WebClientResponseException$BadRequest: 400 Bad Request from POST https://share.opendatahub.testingmachine.eu/json/pushRecords/ON_DEMAND_ITINERARY
app_1  | 	at org.springframework.web.reactive.function.client.WebClientResponseException.create(WebClientResponseException.java:179) ~[spring-webflux-5.2.13.RELEASE.jar:5.2.13.RELEASE]
app_1  | 	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
app_1  | Error has been observed at the following site(s):
app_1  | 	|_ checkpoint ⇢ 400 from POST https://share.opendatahub.testingmachine.eu/json/pushRecords/ON_DEMAND_ITINERARY [DefaultWebClient]
app_1  | Stack trace:
app_1  | 		at org.springframework.web.reactive.function.client.WebClientResponseException.create(WebClientResponseException.java:179) ~[spring-webflux-5.2.13.RELEASE.jar:5.2.13.RELEASE]
app_1  | 		at org.springframework.web.reactive.function.client.DefaultClientResponse.lambda$createException$1(DefaultClientResponse.java:206) ~[spring-webflux-5.2.13.RELEASE.jar:5.2.13.RELEASE]
app_1  | 		at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:100) ~[reactor-core-3.3.14.RELEASE.jar:3.3.14.RELEASE]
app_1  | 		at reactor.core.publisher.FluxDefaultIfEmpty$DefaultIfEmptySubscriber.onNext(FluxDefaultIfEmpty.java:93) ~[reactor-core-3.3.14.RELEASE.jar:3.3.14.RELEASE]
app_1  | 		at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:121) ~[reactor-core-3.3.14.RELEASE.jar:3.3.14.RELEASE]
app_1  | 		at reactor.core.publisher.FluxContextStart$ContextStartSubscriber.onNext(FluxContextStart.java:96) ~[reactor-core-3.3.14.RELEASE.jar:3.3.14.RELEASE]
app_1  | 		at reactor.core.publisher.FluxMapFuseable$MapFuseableConditionalSubscriber.onNext(FluxMapFuseable.java:287) ~[reactor-core-3.3.14.RELEASE.jar:3.3.14.RELEASE]
app_1  | 		at reactor.core.publisher.FluxFilterFuseable$FilterFuseableConditionalSubscriber.onNext(FluxFilterFuseable.java:330) ~[reactor-core-3.3.14.RELEASE.jar:3.3.14.RELEASE]
app_1  | 		at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1812) ~[reactor-core-3.3.14.RELEASE.j
```

**Comment by rcavaliere** [comment]
@noctho can you please have a look at this?

**Comment by noctho** [comment]
Unfortunately I was not able to reproduce this exception. On my local machine the pushData method to my local bdp-core works without exception ... I added some logs of the passed json to check that the json is generated correctly.

Anyway, I noted that the vehicle data in the active activities api are now complete. I found a small problem with the data collector, which I have now fixed.

See my new PR #293

**Comment by rcavaliere** [comment]
@noctho has made a first implementation of the DC. Works and it has already tested. Proposed a change for the management of the vehicle data, so that they can be immediately available through the ODH API.

**Comment by Piiit** [comment]
@rcavaliere Is this ready to be put into production, or do we still wait for your proposed vehicle data change?

**Comment by rcavaliere** [comment]
@Piiit we can put this DC in production as well. Can you do this?

**Comment by Piiit** [comment]
@rcavaliere I will try to do this now

**Comment by Piiit** [comment]
Done... @rcavaliere please test again on production to be sure

**Comment by rcavaliere** [comment]
@Piiit seems to be OK, thanks!
