### ISSUE TITLE
Migrate all DC to the new dc-interface (SDK) version and introduce dashboards and Github Action CI/CD

### ISSUE THREAD

**Issue by Piiit** [noi-techpark/bdp-commons#511]
See [BURNDOWN](https://docs.google.com/spreadsheets/d/1T1kpA61oAouYV8TRWP3S8pPWW_aCX8xK-7G2Ip040jQ/edit#gid=1331789442)

- [x] Github Action CI / CD
- [x] New dc-interface
- [x] New dependencies
- [x] .env configuration
- [x] JSON logging
- [x] Dashboards on Grafana (automatically generated)
  > Dashboards for regular stations work, data collectors with only events do not work right now, those need another template
- [x] Alerting
  (#539)
  > NEW ISSUE FOR THIS: I removed the data collector Grafana alerts for now, since they spam us too much, so we do not find any problems anymore... some warnings or errors are not in our hand, and Grafana is not the right tool for just sending logs on error, we do not have a timeline with a threshold, just a error or warn log, that needs to be send as email. The best would be to have it bundled with all similar alert per hour, or per day... or granular configurable. We need another tool for that.
- [x] Healthcheck + Stats
  (#541)
  > NEW ISSUE FOR THIS
