### ISSUE TITLE
EPIC: As Digiway I would like to integrate several realt-ime and static datastreams related in particular to the status of the hiking routes in the EUREGIO

### ISSUE THREAD

**Issue by rcavaliere** [noi-techpark/bdp-commons#679]

**Comment by rcavaliere** [comment]
@RudiThoeni can you provide me some more technical reference on how e.g. existing hiking routes are currently stored and modeled in the Open Data Hub, so that we can start analyzing how could think to import also these new datasets? 

In the documentation above you can find for the different datasets the end-points we should consider (WFS services). For each service we have a method "getCapabilities" with some metadata information. The geometry and other useful fields are in the "getFeature" methods.

**Comment by rcavaliere** [comment]
ok, if I try to map e.g. in a document existing fields in the WFS services with such data model, then it should be quite easy to integrate these datasets, or? We will mostly have in this case the geometry and some fields, no images.

**Comment by RudiThoeni** [comment]
Yes maybe with the gps position it is mappable....  normally the starting position is saved as GPS Point....... so i think by checking if the gps point is on the Geometry of the WFS data it could be matchable...... however not 100% because often the startingpoint of a hiking route could be is the same for other hiking routes..... 

Here we have to check if it is possible........

**Comment by RudiThoeni** [comment]
Ah now i understand you want to import the data into the content api.... yes if the minimum data is there at least one title/desc + gps point and a category (hike route, bike route) then it should be no problem...... only for the tracks i have to see how to store it because until now it was only links to existing gpx file etc....

**Comment by RudiThoeni** [comment]
Ah now i understand you want to import the data into the content api.... yes if the minimum data is there at least one title/desc + gps point and a category (hike route, bike route) then it should be no problem...... only for the tracks i have to see how to store it because until now it was only links to existing gpx file etc....

**Comment by RudiThoeni** [comment]
todo check the links

**Comment by rcavaliere** [comment]
@RudiThoeni if you want to start look at something, check this: https://geoservices1.civis.bz.it/geoserver/p_bz-TransportNetwork/ows?service=WFS&version=2.0.0&request=getFeature&typeName=p_bz-TransportNetwork:Routes-Cycleways-Tyrol&outputFormat=application/json I found a way to have user friendly JSON interfaces. At the end what we need to manage is the geometry of the different routes, and also the conversion into the WGS84 format of the coordinates, so that they are available in the Google format.

**Comment by RudiThoeni** [comment]
ok i will check this.

**Comment by RudiThoeni** [comment]
On Testing 

Imported data from
https://geoservices1.civis.bz.it/geoserver/p_bz-TransportNetwork/ows?service=WFS&version=2.0.0&request=getFeature&typeName=p_bz-TransportNetwork:Routes-Cycleways-Tyrol&outputFormat=application/json

TO:
https://api.tourism.testingmachine.eu/v1/ODHActivityPoi?source=civis.geoserver

The Geodata is referenced in 
`
"GpsTrack": [
{
"Id": "routes-cycleways-tyrol.19461",
"Type": "Track",
"Format": "geojson",
"GpxTrackUrl": "https://api.tourism.testingmachine.eu/v1/GeoShape/routes-cycleways-tyrol.19461",
"GpxTrackDesc": null
}
],
`

The Shapes Api is used to store the Data
I added support for three formats
https://api.tourism.testingmachine.eu/v1/GeoShape/routes-cycleways-tyrol.19461  (Standard EPSG:4326)
https://api.tourism.testingmachine.eu/v1/GeoShape/routes-cycleways-tyrol.19461?srid=3857  (Mercator)
https://api.tourism.testingmachine.eu/v1/GeoShape/routes-cycleways-tyrol.19461?srid=32632  (EPSG:32632)

**Comment by rcavaliere** [comment]
@RudiThoeni wonderful! I would suggest to make the same with the other GIS resources provided by the Province of Bolzano, e.g.:

- [ ] Mountain bikes routes: https://geoservices1.civis.bz.it/geoserver/p_bz-TransportNetwork/ows?service=WFS&version=2.0.0&request=getFeature&typeName=p_bz-TransportNetwork:Routes-MTB&outputFormat=application/json
- [ ] Hiking trails: https://geoservices1.civis.bz.it/geoserver/p_bz-TransportNetwork/ows?service=WFS&version=2.0.0&request=getFeature&typeName=p_bz-TransportNetwork:Routes-HikingTrails&outputFormat=application/json
- [ ]  Intermunicipal cycling routes: https://geoservices1.civis.bz.it/geoserver/p_bz-TransportNetwork/ows?service=WFS&version=2.0.0&request=getFeature&typeName=p_bz-TransportNetwork:Routes-CyclewaysIntermunicipalPaths&outputFormat=application/json

I have some doubts regarding the end-point for the car road network, I have to ask the Province. 

In general, other territories will have the services as XML and not as JSON, will this be an issue for us? The data structure is going to be very similar

**Comment by rcavaliere** [comment]
@RudiThoeni thanks for your work!

If I look at the map view of the Data Browser it seems that we have a lot of data:

![Image](https://github.com/user-attachments/assets/3819133f-1bfa-4607-b34a-4b44c7f01cae)

For better assessing the data quality of each dataset, maybe it is possible to separate the different datasets?

Before returning to the partners with your inputs, let me first check the web-services provided and also the amount of information they show on https://mapview.civis.bz.it. Maybe there is still some fine-tuning work in the way we integrate this data...

By the way, the web-component we should develop should also be able to show the GPS track. Maybe are we able with the support of the Customer Care to make a first attempt to show this data in https://webcomponents.opendatahub.testingmachine.eu/webcomponent/activity-and-poi?

**Comment by rcavaliere** [comment]
> Hi [@rcavaliere](https://github.com/rcavaliere)
> 
> I integrated the data on test **Api** All Pois--> https://api.tourism.testingmachine.eu/v1/ODHActivityPoi?source=civis.geoserver All Shapes --> https://api.tourism.testingmachine.eu/v1/GeoShapes?source=civis.geoserver
> 
> hikingtrails --> https://api.tourism.testingmachine.eu/v1/ODHActivityPoi?source=civis.geoserver.hikingtrails cyclewaystyrol --> https://api.tourism.testingmachine.eu/v1/ODHActivityPoi?source=civis.geoserver.cyclewaystyrol mountainbikeroutes --> https://api.tourism.testingmachine.eu/v1/ODHActivityPoi?source=civis.geoserver.mountainbikeroutes intermunicipalcyclingroutes --> https://api.tourism.testingmachine.eu/v1/ODHActivityPoi?source=civis.geoserver.intermunicipalcyclingroutes
> 
> **Databrowser** I created a Dataset for Digiway Data in the Databrowser (we can change the naming) where the data is directly filtered https://databrowser.opendatahub.testingmachine.eu/dataset/table/tourism/v1/ODHActivityPoi?source=civis.geoserver
> 
> as described below there is not much metadata available, it could be possible to enrich some data based on the gps point like region, etc... but lets discuss this..........
> 
> If you click on a record there is available GpsPoint / GpsTrack etc... As Tags for the Activity/Poi i added the Tags present in Open Data Hub Tags that could match (cycling etc...)....
> 
> Issues:
> 
>     1. Id
> 
> 
> What is very strange is the ID of the data. It seems the ID increases after some time Here an example of the Intermunicipal Cycleway Höhlensteintal
> 
> Höhlensteintal 2025-04-24 22:06:23.429 routes-cyclewaysintermunicipalpaths.112882 2025-04-23 11:31:33.509 routes-cyclewaysintermunicipalpaths.112662 today routes-cyclewaysintermunicipalpaths.122342
> 
> For updating data this could possible be an issue...... i need an unique identifier here
> 
>     2. Metadata
> 
> 
> At example there are hiking trails with no name, no code etc....
> 
> `"properties":{"ID":10212670,"CODE":null,"NAME":"...","CODE_NAME":"...","LENGTH_GEOM":1882}`
> 
> this looks like this on the databrowser ;)))
> 
> ![Image](https://github.com/user-attachments/assets/628e48f3-7e5e-4294-9725-aae49d699b1f)

One question here: did you also import the road network (

Road network South Tyrol, available via WFS service:
https://geoservices1.civis.bz.it/geoserver/p_bz-TransportNetwork/ows?service=WFS&version=2.0.0&request=getCapabilities
https://geoservices1.civis.bz.it/geoserver/p_bz-TransportNetwork/ows?service=WFS&version=2.0.0&request=getFeature&typeName=p_bz-TransportNetwork:LinksSequences-Labels)?

**Comment by ohnewein** [comment]
@rcavaliere on one hand I do not like proxy implementations, because they are not real implementations. But on the other hand I would also not like to fill up our DB with data nobody will ever use.

Therefore I have a similar question as @RudiThoeni , what are the use cases of this data? Can we name some or is there no known use case existing?

**Comment by ohnewein** [comment]
@rcavaliere I would suggest to follow our mantra: "Use Case first!".

Ideally a use case defined by an external stakeholder. But if that's not yet possible, we can also accept internally defined use cases. But I think we have to create a description of a use case, in which there is some sort of data visualization and value creation for a user, before we start implementing additional APIs.

Otherwise we create a clutter of APIs and add complexity for all developers without adding any value.
