### ISSUE TITLE
As a project manager, I would like to have a way to automatically manage the A22 VPN for connecting to the platform managing the innovative air quality measurements

### ISSUE THREAD

**Issue by rcavaliere** [noi-techpark/bdp-commons#94]
More specifically: the VPN client is CheckPoint VPN. An alternative to the Windows client has to be found. Credentials have been already shared.

**TODOS**
- [x] Try to find a linux vpn client and use that to connect to the A22 VPN
> Not possible, `snx` crashes continuously, A22 does not provide enough parameters to use a generic VPN client as `ike` or `shrew`.
- [x] Install a windows machine on AWS
> We use the MacBook in our office now (no longer any Windows machine)
- [x] Install the VPN client (checkpoint) with A22 credentials
- [x] Install a proxy on the windows machine to pipe through the VPN tunnel
- [x] Connect to the windows proxy from a linux client
> Invalid: We use a reverse SSH tunnel for that now, not a proxy
> ssh -N -L 19999:192.168.45.35:61616 idm@10.161.88.10
- [x] Open a resource behind the A22 VPN from the linux client
- [ ] Configure the MacBook with the reverse tunnel pointing to the DC server and configure it to keep the VPN and tunnel open
- [ ] Write a pipeline to deploy the A22 Data Collector on the DC server and connect there to localhost:<some-port> that connects to the VPN MQTT broker via the tunnel
- [ ] Write a documentation on how everything was setup

**Comment by Piiit** [comment]
There is a linux client, but quite old (it still uses i386 32bit libraries). I had no luck until now to connect to the VPN. There are other options, like "ike" or "shrew", but for them I would need much more detailed server information. @rcavaliere Could you please ask A22 about there experiences with linux or ask them about additional information, like encryption algorithm etc... (see email)

**Comment by rcavaliere** [comment]
@Piiit as I expected A22 does not want to remove the VPN obstacle, and unfortunately they do not support Linux clients. They suggested to foresee a Windows virtual machine. Is this possible?

**Comment by Piiit** [comment]
@rcavaliere Yes, that is possible, but costly... We would need a Windows machine just as a proxy.

**Comment by rcavaliere** [comment]
@Piiit let's do like this. I will try to convince A22 next week. If I don't manage to do it, we will discuss this internally at the next sprint meeting how to proceed.

**Comment by Piiit** [comment]
Testing can be done with a MQTT client https://www.hivemq.com/blog/seven-best-mqtt-client-tools/

**Comment by bertolla** [comment]
@rcavaliere 
Reverse Tunnel + vpn is ready, but a big Problem is that we loose connection to the VPN after a couple of minutes. 
Could you ask a22 why that is and if they can resolve the issue?
Thx,
Patrick

**Comment by rcavaliere** [comment]
@bertolla good to hear this, I have asked A22 for support in the open issue left.

**Comment by bertolla** [comment]
No news?

**Comment by rcavaliere** [comment]
Unfortunately not at the moment. Will let you know...

**Comment by Piiit** [comment]
On MAC we get a drop of connection after max. 2 minutes. Maybe it is a local network issue. I have already asked Berni, which has a cooperation with someone from UNIBZ not earlier than 3 July. Another solution would be to use the windows machine on AWS. The VPN client installation went well and we have a ssh tunnel to that machine as well. But our script would need to be ported to the powershell, I suggest to wait for Berni therefore.

**Comment by rcavaliere** [comment]
Quick update from my side: alternative solution as the one we discussed at the last Sprint Meeting should be feasibile, waiting for final ACK.

**Comment by rcavaliere** [comment]
News from Gianluca Antonacci: he told me that he found a client working on Fedora that could also manage the automatic connection every 8 hours.
Details here:

Qui ci sono le istruzioni che ho usato io su Fedora (in realtà avevo già tutte le dipendenze soddisfatte)
https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fblog.gordonbuchan.com%2Fblog%2Findex.php%2F2018%2F12%2F30%2Fconnecting-to-a-checkpoint-vpn-from-fedora-29%2F&amp;data=01%7C01%7Cr.cavaliere%40noi.bz.it%7Cd28cb6af8898478e917808d7111e82ed%7Cb6acf547c3524708a725ec0e662c5d11%7C0&amp;sdata=zwN%2BcRGgyI1dPgqeY5HaBozMTs4y7bm3vgj9fqQRHQo%3D&amp;reserved=0

Qui le istruzioni generali con il link per scaricare il client
https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgist.github.com%2Frkueny%2F301f7ead21ed2a0ee8bbe2d755bed90b&amp;data=01%7C01%7Cr.cavaliere%40noi.bz.it%7Cd28cb6af8898478e917808d7111e82ed%7Cb6acf547c3524708a725ec0e662c5d11%7C0&amp;sdata=KAqBw1Oit%2FujrW2QV8mB80oGRb0LUaqUv4Bq10rK67g%3D&amp;reserved=0

Da me il client gira, ovviamente bisogna verificare se funziona specificatamente con la versione server di A22. In effetti nei commenti sopra riportati (2° link) si parla - come dicevi tu - delle diverse release del fatto che sui server nuovi i vecchi client non vanno più. Però questa mattina ho guardato da Lorenzo e compariva una build del client 800008064, mentre questa sarebbe successiva, ovvero 800007075
Vedi tu se vale la pena fare una rapida prova

Gianluca 

@Piiit can you make a try?

**Comment by rcavaliere** [comment]
@Piiit stop tests if you started them. I managed to agree with A22 that we don't need a VPN anymore. We will get access through HTTPS, calls will be possible only from a static IP address.

**Comment by Piiit** [comment]
@rcavaliere This are good news. So I will wait until the path of open for regular retrievals. Let me know, what you need.
